apiVersion: v1
kind: Service
metadata:  
  labels:
    app: worker-service-app
  name: worker-service-app
  namespace: worker-service
  resourceVersion: "1584"  
spec:
  clusterIP: 10.96.166.88
  clusterIPs:
  - 10.96.166.88
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31188
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: worker-service-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}