apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default  
spec:  
  replicas: 1  
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - image: bkimminich/juice-shop:latest
        imagePullPolicy: Always
        name: juice-shop
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler     
