apiVersion: v1
kind: Service
metadata:  
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default  
spec:
  clusterIP: 10.96.166.40
  clusterIPs:
  - 10.96.166.40
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31123
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: kubernetes-bootcamp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}