apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-19T18:11:08Z"
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default
  resourceVersion: "1584"
  uid: d8a2a2fb-0b70-4fc5-a6e8-beaab0612924
spec:
  clusterIP: 10.96.166.40
  clusterIPs:
  - 10.96.166.40
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31123
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: kubernetes-bootcamp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}