apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-dev
spec:      
  containers:
  - name: minio
    image: quay.io/minio/minio:latest  
    command: 
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
    volumeMounts:
    - name: storage 
      mountPath: "/storage"
  volumes:
  - name: storage
    persistentVolumeClaim:          
      claimName: minio-pv-1
  