apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-dev
spec:      
  containers:
  - name: minio
    image: quay.io/minio/minio:latest  
    command: ["minio"]
    args: ["server", "/storage"]
    volumeMounts:
    - name: storage 
      mountPath: "/storage"
  volumes:
  - name: storage
    persistentVolumeClaim:          
      claimName: minio-pv-1
  