version: 1.0
configuration:
  showDiagnosticInformation: false
  defaultCommand: commands
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022
  backupPath: ..\..\..\..\Core\PainKiller.PowerCommands.Core\  
  defaultGitRepositoryPath: ..\..\..\..\..\  
  kubernetesDeploymentFilesRoot: ..\..\..\..\..\src\
  kubernetesDashboardUrl:  http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
  metadata:
    name: Kubernetes Client
    description: K8:s commands
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 13b9944b55efe60362720a679f17a22c
    name: Serialog
  components:
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 4f04313db8e67b2bc4b059c478a900af
    name: PainKiller Core
  - component: PainKiller.PowerCommands.KubernetesCommands.dll
    checksum: a2df61ea89e4f9ec265d921bfad87193
    name: Kubernetes Commands  
  secret:
    secrets:    
  environment:
    variables:
    - name: OS
      environmentVariableTarget: Machine