version: 1.0
configuration:
  showDiagnosticInformation: false
  defaultCommand: k
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022
  backupPath: ..\..\..\..\Core\PainKiller.PowerCommands.Core\  
  defaultGitRepositoryPath: ..\..\..\..\
  pathToDockerDesktop: C:\Program Files\Docker\Docker
  loginShellCommand: 
  metadata:
    name: PowerKubernetes
    description: kubectl client
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 13b9944b55efe60362720a679f17a22c
    name: Serialog
  components:
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 4f04313db8e67b2bc4b059c478a900af
    name: PainKiller Core
  - component: PainKiller.PowerCommands.KubernetesCommands.dll
    checksum: a2df61ea89e4f9ec265d921bfad87193
    name: Kubernetes Commands 
  bookmark:
    bookmarks:
    - name: manifests
      path: C:\Repos\Github\PowerKubernetes\manifests
      index: 0
    - name: tutorial
      path: C:\Repos\Github\KubernetesTutorials\manifests
      index: 1