apiVersion: apps/v1
kind: Deployment
metadata:  
  generation: 1
  labels:
    app: worker-service-app
  name: worker-service-app
  namespace: worker-service  
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker-service-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-service-app
    spec:
      containers:
      - image: dockerdoktor/workerservicetutorialwebapi
        imagePullPolicy: Always
        name: workerservicetutorialwebapi01
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File      
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}