apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-worker-service-job
  namespace: worker-service  
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-worker-service-job01
            image: dockerdoktor/myworkerservice
            env:
            - name: WebApiUrl
              value: "https://10.96.166.88:31188/api"
          restartPolicy: OnFailure